// in public/sounds
export default [
  'pot-hit-1_c.mp3',
  'pot-hit-2_c.mp3',
  'balsa-hit-0_c.mp3',
  'balsa-hit-2_c.mp3',
  'balsa-hit-7_c.mp3',
  'cuenco-metal_c.mp3',
  'cuenco-metal2_c.mp3',
  'zippo-click_c.mp3',
  'zippo-scratch_c.mp3',
  'Va-pizz-sec-AD4-ff-2c_c.mp3',
  'BbCl-ord-C4-mf_c.mp3',
  'basse_2_faD_sto_c.mp3',
  'tenor_4_sol--_sto_c.mp3',
  'soprano_6_do_stei_67_c.mp3',
  'cymbalum_ForteDo1_c.mp3',
  'Mridangam.c_c.mp3',
  'Mridangam.d_c.mp3',
  'Mridangam.h_c.mp3',
  'Mridangam.i_c.mp3',
  'Mridangam.l_c.mp3',
  'growl_40-3_c.mp3',
  'growl_43-2_c.mp3',
  'tettigonia-cantans_c.mp3'
];
